### ISSUE TITLE
Propose ITE for how to best integrate in-toto + TUF

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/ITE#3]
A recommendation ITE that explains how to best integrate in-toto + [TUF](/theupdateframework/tuf) would be useful to guide users who want to use both technologies together.

**Comment by trishankatdatadog** [comment]
Let's do this 👍

Should we start writing an ITE here off a branch here, or use a Google Doc first?

**Comment by SantiagoTorres** [comment]
Either way works for me, I just wanted it to  be tracked for our ROADMAP purposes. Let's do the doc as we discussed yesterday :)

**Comment by trishankatdatadog** [comment]
I think we can close this thanks to #4 and #5

**Comment by SantiagoTorres** [comment]
yep, thanks!
